# Generated by Django 4.2.3 on 2023-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=' نام')),
                ('family_name', models.CharField(max_length=100, verbose_name=' نام خانوادگی')),
                ('father_name', models.CharField(max_length=100, verbose_name=' نام پدر')),
                ('national_code', models.CharField(max_length=20, verbose_name=' کد ملی')),
                ('shenasname_code', models.CharField(max_length=20, verbose_name=' شماره شناسنامه')),
                ('birth_date', models.CharField(max_length=20, verbose_name=' تاریخ تولد')),
                ('birth_place', models.CharField(max_length=100, verbose_name=' محل تولد')),
                ('bimeh_code', models.CharField(max_length=20, verbose_name=' شماره بیمه')),
                ('tel', models.CharField(max_length=20, verbose_name=' شماره تلفن ثابت')),
                ('mobile', models.CharField(max_length=20, verbose_name=' تلفن همراه')),
                ('madrak_tahsili', models.CharField(max_length=100, verbose_name=' مدرک تحصیلی')),
                ('mahale_faliat', models.CharField(max_length=100, verbose_name=' محل فعالیت')),
                ('semat', models.CharField(max_length=100, verbose_name=' سمت')),
                ('address', models.CharField(max_length=100, verbose_name=' آدرس')),
                ('postal_code', models.CharField(max_length=20, verbose_name=' کد پستی')),
            ],
            options={
                'verbose_name': 'اطلاعات کارمندان',
                'verbose_name_plural': 'اطلاعات کارمندان',
            },
        ),
    ]
