# Generated by Django 4.2.5 on 2023-09-06 14:14

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0003_employee_information_sherkat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_information',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='karmandan/profile/'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='bimeh_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره بیمه'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, max_length=20, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محل تولد'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='mahale_faliat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محل فعالیت'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='national_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='semat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='shenasname_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن ثابت'),
        ),
    ]
