# Generated by Django 4.2.5 on 2023-09-06 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0004_employee_information_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_information',
            name='folan_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='karmandan/profile/', verbose_name='عکس پروفایل'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='karmandan/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='فایل')),
                ('karmand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='Karmandan.employee_information', verbose_name='نام')),
            ],
        ),
    ]
