# Generated by Django 4.2.5 on 2023-09-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0005_employee_information_folan_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
    ]
