# Generated by Django 4.2.3 on 2023-09-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0013_alter_company_insurance_information_company_insurance_information_and_more'),
        ('Karmandan', '0007_alter_file_karmand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'بارگذاری مدارک', 'verbose_name_plural': 'بارگذاری مدارک ها'},
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='family_name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='national_code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='sherkat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='Sherkat.general_company_information', verbose_name='نام شرکت/موسسه'),
        ),
        migrations.AlterField(
            model_name='file',
            name='karmand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='Karmandan.employee_information', verbose_name=' نام و نام خانوادگی '),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدرک'),
        ),
    ]
