# Generated by Django 4.2.5 on 2023-09-08 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0009_remove_file_karmand_employee_information_docs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_information',
            name='folan_file',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='فایل'),
        ),
    ]
