# Generated by Django 4.2.3 on 2023-09-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0016_alter_file_file_and_more'),
        ('Karmandan', '0011_delete_file_alter_employee_information_docs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_information',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='karmandan', to='Sherkat.file', verbose_name='مدارک'),
        ),
    ]
