# Generated by Django 4.2.3 on 2023-09-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0012_alter_employee_information_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_information',
            options={'verbose_name': 'اطلاعات کارمندان', 'verbose_name_plural': 'اطلاعات کارمندان'},
        ),
    ]
