# Generated by Django 4.2.3 on 2023-09-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0014_phone_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone_book',
            name='email',
        ),
    ]
