# Generated by Django 4.2.3 on 2023-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0015_remove_phone_book_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone_book',
            old_name='address',
            new_name='address_phonebook',
        ),
        migrations.RenameField(
            model_name='phone_book',
            old_name='dakheli',
            new_name='dakheli_phonebook',
        ),
        migrations.RenameField(
            model_name='phone_book',
            old_name='family_name',
            new_name='family_name_phonebook',
        ),
        migrations.RenameField(
            model_name='phone_book',
            old_name='mobile',
            new_name='mobile_phonebook',
        ),
        migrations.RenameField(
            model_name='phone_book',
            old_name='name',
            new_name='name_phonebook',
        ),
        migrations.RenameField(
            model_name='phone_book',
            old_name='sherkat',
            new_name='name_sherkat',
        ),
        migrations.RenameField(
            model_name='phone_book',
            old_name='postal_code',
            new_name='postal_code_phonebook',
        ),
        migrations.RenameField(
            model_name='phone_book',
            old_name='rabet_name',
            new_name='rabet_name_phonebook',
        ),
        migrations.RenameField(
            model_name='phone_book',
            old_name='semat',
            new_name='semat_phonebook',
        ),
        migrations.RenameField(
            model_name='phone_book',
            old_name='tel',
            new_name='tel_phonebook',
        ),
        migrations.AddField(
            model_name='phone_book',
            name='email_phonebook',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
