# Generated by Django 4.2.3 on 2023-09-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0016_rename_address_phone_book_address_phonebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_book',
            name='mobile_phonebook',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='phone_book',
            name='tel_phonebook',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن ثابت'),
        ),
    ]
