# Generated by Django 4.2.5 on 2023-09-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0017_alter_phone_book_mobile_phonebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_book',
            name='fax_phonebook',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره فکس'),
        ),
    ]
