# Generated by Django 4.2.5 on 2023-09-19 12:11

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0018_phone_book_fax_phonebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_information',
            name='end_date_of_work',
            field=django_jalali.db.models.jDateField(blank=True, max_length=20, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='employee_information',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('M', 'مجرد'), ('MO', 'متاهل'), ('SA', 'سایر')], max_length=10, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AddField(
            model_name='employee_information',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, max_length=20, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='employee_information',
            name='tedade_farzand',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد فرزند'),
        ),
    ]
