# Generated by Django 4.2.5 on 2023-09-19 13:06

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0019_employee_information_end_date_of_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_information',
            name='reshte_tahsili',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='end_date_of_work',
            field=django_jalali.db.models.jDateField(blank=True, max_length=20, null=True, verbose_name='تاریخ اتمام قرار داد'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('mo', 'مجرد'), ('ma', 'متاهل'), ('sa', 'سایر')], max_length=100, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, max_length=20, null=True, verbose_name='تاریخ شروع به کار'),
        ),
    ]
