# Generated by Django 4.2.5 on 2023-09-20 11:07

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0020_employee_information_reshte_tahsili_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_information',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='end_date_of_work',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ اتمام قرار داد'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع به کار'),
        ),
    ]
