# Generated by Django 4.2.5 on 2023-10-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0021_alter_employee_information_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_information',
            name='check_box',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='دارای فعالیت'),
        ),
        migrations.AddField(
            model_name='employee_information',
            name='sex',
            field=models.CharField(choices=[('f', 'زن'), ('m', 'مرد'), ('s', 'سایر')], max_length=2, null=True, verbose_name='جنسیت'),
        ),
    ]
