# Generated by Django 4.2.5 on 2023-10-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0022_employee_information_check_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_information',
            name='birth_place',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='محل تولد'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='family_name',
            field=models.CharField(max_length=20, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='father_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='madrak_tahsili',
            field=models.CharField(blank=True, choices=[('zi', 'زیر دیپلم'), ('di', 'دیپلم'), ('li', 'لیسانس'), ('fo', 'فوق لیسانس'), ('dr', 'دکترا')], max_length=5, null=True, verbose_name=' مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='mahale_faliat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='محل فعالیت'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('mo', 'مجرد'), ('ma', 'متاهل'), ('sa', 'سایر')], max_length=5, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='national_code',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='noe_gharardad',
            field=models.CharField(blank=True, choices=[('gh', 'قراردادی'), ('py', 'پیمانی'), ('da', 'دوامی'), ('sa', 'ساعتی'), ('di', 'دیگر')], max_length=5, null=True, verbose_name='نوع قرارداد'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='semat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='shenasname_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تلفن ثابت'),
        ),
    ]
