# Generated by Django 4.2.3 on 2023-10-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0023_alter_employee_information_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee_information',
            table='employee_information',
        ),
        migrations.AlterModelTable(
            name='phone_book',
            table='phone_book',
        ),
    ]
