# Generated by Django 4.2.5 on 2023-10-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0024_alter_employee_information_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_information',
            name='shenasname_photo',
            field=models.ImageField(blank=True, null=True, upload_to='karmandan/shenasnameh/', verbose_name='عکس شناسنامه'),
        ),
    ]
