# Generated by Django 4.2.3 on 2023-10-15 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0025_employee_information_shenasname_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_information',
            name='shenasname_photo',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل'),
        ),
    ]
