# Generated by Django 4.2.3 on 2023-10-15 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0026_alter_employee_information_shenasname_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_information',
            name='shenasname_photo',
        ),
        migrations.AddField(
            model_name='employee_information',
            name='bimeh_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/bimeh/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='بارگذاری مدرک بیمه'),
        ),
        migrations.AddField(
            model_name='employee_information',
            name='cartmeli_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/melicard/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='بارگذاری کارت ملی'),
        ),
        migrations.AddField(
            model_name='employee_information',
            name='gharardad_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/gharardad/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='بارگذاری قرارداد'),
        ),
        migrations.AddField(
            model_name='employee_information',
            name='madrak_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/madrak/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='بارگذاری مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='employee_information',
            name='shenasname_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/shenasname/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='بارگذاری شناسنامه'),
        ),
    ]
