# Generated by Django 4.2.5 on 2023-10-16 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karmandan', '0027_remove_employee_information_shenasname_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_information',
            name='bimeh_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/bimeh/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل مدارک بیمه'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='cartmeli_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/melicard/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل کارت ملی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='family_name',
            field=models.CharField(max_length=24, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='gharardad_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/gharardad/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل قرارداد'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='madrak_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/madrak/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='employee_information',
            name='shenasname_file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/shenasname/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل شناسنامه'),
        ),
        migrations.AlterField(
            model_name='phone_book',
            name='mobile_phonebook',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='تلفن همراه'),
        ),
    ]
