# Generated by Django 4.2.3 on 2023-07-30 17:22

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0002_alter_general_company_information_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_insurance_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز عبور')),
                ('office_insurance_workshop_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد کارگاهی بیمه دفتر')),
                ('Name_office_insurance_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شعبه ی بیمه کارخانه')),
                ('factory_insurance_workshop_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد کارگاهی بیمه کارخانه')),
            ],
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='company_registration_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ثبت شرکت'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=' کد پستی دفتر'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='postal_code_factory',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی کارخانه'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='tel_fax',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره فکس'),
        ),
    ]
