# Generated by Django 4.2.3 on 2023-08-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0004_alter_company_insurance_information_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tax_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کلاسه(شماره پرونده)')),
                ('tax_center', models.CharField(blank=True, max_length=100, null=True, verbose_name='مرکز مالیاتی')),
                ('tax_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='حوزه مالیاتی')),
                ('tax_tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری مالیاتی')),
                ('tax_address', models.TextField(blank=True, max_length=100, null=True, verbose_name=' آدرس حوزه مالیاتی')),
                ('value_added_information', models.CharField(blank=True, max_length=100, null=True, verbose_name='اطلاعات مالیات بر ارزش افزوده')),
                ('username_value_information', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='(نام کاربری)')),
                ('password_value_information', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='(رمز عبور)')),
                ('quarterly_tax_information', models.CharField(blank=True, max_length=100, null=True, verbose_name='اطلاعات مالیات فصلی (TTMS)')),
                ('username_quarterly_tax_information', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='(نام کاربری)')),
                ('password_quarterly_information', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='(رمز عبور)')),
            ],
            options={
                'verbose_name': 'اطلاعات مالیاتی شرکت',
                'verbose_name_plural': 'اطلاعات مالیاتی شرکت ها',
            },
        ),
    ]
