# Generated by Django 4.2.3 on 2023-08-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0005_tax_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_insurance_information',
            name='general_company_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_insurance_information', to='Sherkat.general_company_information', verbose_name='نام شرکت / موسسه'),
        ),
    ]
