# Generated by Django 4.2.3 on 2023-08-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0009_rename_company_insurance_information_company_insurance_information_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_insurance_information',
            old_name='title',
            new_name='company_insurance_information',
        ),
        migrations.RenameField(
            model_name='tax_information',
            old_name='title',
            new_name='general_company_information',
        ),
    ]
