# Generated by Django 4.2.5 on 2023-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0013_alter_company_insurance_information_company_insurance_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_company_information',
            name='company_activity',
            field=models.CharField(choices=[('T', 'تولیدی'), ('B', 'بازرگانی'), ('KH', 'خدماتی'), ('P', 'پیمانکاری')], max_length=2, null=True, verbose_name='فعالیت شرکت'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='national_id',
            field=models.CharField(max_length=20, null=True, verbose_name='شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='نام شرکت / موسسه'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='type_activity',
            field=models.CharField(choices=[('sa', 'سهامی عام'), ('sakh', 'سهامی خاص'), ('m', 'مسئولیت محدود'), ('n', 'نسبی'), ('t', 'تضامنی'), ('s', 'سهامی'), ('ghs', 'غیر سهامی'), ('ttm', 'تعاونی تولید و مصرف')], max_length=4, null=True, verbose_name='نوع شرکت'),
        ),
    ]
