# Generated by Django 4.2.5 on 2023-09-08 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0014_alter_general_company_information_company_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدرک')),
                ('file', models.FileField(blank=True, null=True, upload_to='karmandan/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'بارگذاری مدارک',
                'verbose_name_plural': 'بارگذاری مدارک',
            },
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی دفتر'),
        ),
        migrations.AlterField(
            model_name='tax_information',
            name='tax_address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='آدرس حوزه مالیاتی'),
        ),
        migrations.AddField(
            model_name='company_insurance_information',
            name='docs',
            field=models.ManyToManyField(blank=True, to='Sherkat.file', verbose_name='مدارک'),
        ),
        migrations.AddField(
            model_name='general_company_information',
            name='docs',
            field=models.ManyToManyField(blank=True, to='Sherkat.file', verbose_name='مدارک'),
        ),
        migrations.AddField(
            model_name='tax_information',
            name='docs',
            field=models.ManyToManyField(blank=True, to='Sherkat.file', verbose_name='مدارک'),
        ),
    ]
