# Generated by Django 4.2.3 on 2023-09-09 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0015_file_alter_general_company_information_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='karmandan/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='sherkat', to='Sherkat.file', verbose_name='مدارک'),
        ),
    ]
