# Generated by Django 4.2.3 on 2023-09-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0017_remove_tax_information_quarterly_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sahamdaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sahamdaran', models.CharField(max_length=100, null=True, verbose_name='نام سهامدار')),
                ('family_name_sahamdaran', models.CharField(max_length=100, null=True, verbose_name='نام خانوادگی سهامدار')),
                ('national_code_sahamdaran', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد ملی سهامدار')),
                ('number_sahamdaran', models.CharField(blank=True, max_length=100, null=True, verbose_name='مبلغ سرمایه گذاری/تعداد سهام')),
                ('percent_sahamdaran', models.CharField(blank=True, max_length=100, null=True, verbose_name='درصد سهام')),
                ('docs', models.ManyToManyField(blank=True, to='Sherkat.file', verbose_name='مدارک')),
                ('sherkat_sahamdaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sahamdaran', to='Sherkat.general_company_information', verbose_name='نام شرکت / موسسه')),
            ],
            options={
                'verbose_name': 'اطلاعات سهامداران شرکت',
                'verbose_name_plural': 'اطلاعات سهامداران شرکت ها',
            },
        ),
    ]
