# Generated by Django 4.2.3 on 2023-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0018_sahamdaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahamdaran',
            name='tel_sahamdar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='general_company_information',
            name='sarmaye',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سرمایه شرکت'),
        ),
        migrations.AlterField(
            model_name='sahamdaran',
            name='number_sahamdaran',
            field=models.CharField(max_length=100, null=True, verbose_name='مبلغ سرمایه گذاری/تعداد سهام'),
        ),
    ]
