# Generated by Django 4.2.5 on 2023-09-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0019_sahamdaran_tel_sahamdar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sahamdaran',
            old_name='tel_sahamdar',
            new_name='tel_sahamdaran',
        ),
    ]
