# Generated by Django 4.2.5 on 2023-10-01 12:03

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0021_sahamdaran_noe_masoliat_sahamdaran_semat_sahamdaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahamdaran',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='sahamdaran',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='sahamdaran',
            name='tarikh_tavalod',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
