# Generated by Django 4.2.5 on 2023-10-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0022_sahamdaran_address_sahamdaran_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahamdaran',
            name='father_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='sahamdaran',
            name='noe_shakhs',
            field=models.CharField(choices=[('ho', 'حقوقی'), ('ha', 'حقیقی')], max_length=2, null=True, verbose_name='نوع شخص'),
        ),
        migrations.AddField(
            model_name='sahamdaran',
            name='noe_tabeiat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تابعیت شخص'),
        ),
        migrations.AlterField(
            model_name='sahamdaran',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sahamdaran',
            name='family_name_sahamdaran',
            field=models.CharField(max_length=20, null=True, verbose_name='نام خانوادگی سهامدار'),
        ),
        migrations.AlterField(
            model_name='sahamdaran',
            name='name_sahamdaran',
            field=models.CharField(max_length=20, null=True, verbose_name='نام سهامدار'),
        ),
        migrations.AlterField(
            model_name='sahamdaran',
            name='national_code_sahamdaran',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی سهامدار'),
        ),
        migrations.AlterField(
            model_name='sahamdaran',
            name='tel_sahamdaran',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه'),
        ),
    ]
