# Generated by Django 4.2.3 on 2023-10-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0025_sahamdaran_check_box'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company_insurance_information',
            table='company_insurance_information',
        ),
        migrations.AlterModelTable(
            name='file',
            table='File',
        ),
        migrations.AlterModelTable(
            name='general_company_information',
            table='general_company_information',
        ),
        migrations.AlterModelTable(
            name='sahamdaran',
            table='sahamdaran',
        ),
        migrations.AlterModelTable(
            name='tax_information',
            table='tax_information',
        ),
    ]
