# Generated by Django 4.2.3 on 2023-10-12 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sherkat', '0026_alter_company_insurance_information_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_insurance_information',
            name='Company_insurance_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_insurance_information', to='Sherkat.general_company_information', verbose_name='نام شرکت / موسسه'),
        ),
        migrations.AlterField(
            model_name='company_insurance_information',
            name='factory_insurance_workshop_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد کارگاهی بیمه کارخانه'),
        ),
        migrations.AlterField(
            model_name='company_insurance_information',
            name='name_factory_insurance_branch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام شعبه ی بیمه کارخانه'),
        ),
        migrations.AlterField(
            model_name='company_insurance_information',
            name='name_office_insurance_branch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام شعبه ی بیمه دفتر'),
        ),
        migrations.AlterField(
            model_name='company_insurance_information',
            name='office_insurance_workshop_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد کارگاهی بیمه دفتر'),
        ),
        migrations.AlterField(
            model_name='company_insurance_information',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='company_insurance_information',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='tax_information',
            name='Tax_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_information', to='Sherkat.general_company_information', verbose_name='نام شرکت / موسسه'),
        ),
    ]
